/*
 * Foundations of Parallel Computing II.
 * CUDA implementation of inclusive prefix sum (scan).
 *
 * Input is generated by:
 *   x[i] = (i * 17 + 13) % 1000
 *
 * Three-pass scheme:
 *   1. Per-block local inclusive scan in shared memory (work-efficient
 *      Blelloch up-sweep / down-sweep), each block writes its total sum
 *      to a per-block sums array.
 *   2. Recursively scan the per-block sums array (exclusive scan of the
 *      per-block totals, performed by the same kernel chain).
 *   3. Add the corresponding block offset back to every element of each
 *      block's local result to produce the final inclusive scan.
 *
 * On completion, the result is written to:
 *   scan_N<N>.txt
 *
 * Usage: ./parallel <N>
 */

#include <cuda_runtime.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#define CUDA_CHECK(call)                                                       \
  do {                                                                         \
    cudaError_t err__ = (call);                                                \
    if (err__ != cudaSuccess) {                                                \
      std::cerr << "CUDA error " << cudaGetErrorString(err__) << " at "        \
                << __FILE__ << ":" << __LINE__ << "\n";                        \
      std::exit(1);                                                            \
    }                                                                          \
  } while (0)

// ---------------------------------------------------------------------------
// Tunable parameters
// ---------------------------------------------------------------------------
//
// Each thread processes 2 elements (Blelloch tree on 2*BLOCK_SIZE elements
// per block). BLOCK_SIZE is the number of threads per block.
static const int BLOCK_SIZE = 512;
static const int ELEMENTS_PER_BLOCK = 2 * BLOCK_SIZE;

using Value = long long;

// ---------------------------------------------------------------------------
// Kernel: generate input on the device
// ---------------------------------------------------------------------------
__global__ void generate_input_kernel(Value* x, long long N) {
  long long idx = (long long)blockIdx.x * blockDim.x + threadIdx.x;
  if (idx < N) {
    x[idx] = (idx * 17LL + 13LL) % 1000LL;
  }
}

// ---------------------------------------------------------------------------
// Kernel: per-block inclusive scan using Blelloch's algorithm in shared mem.
//
// Each block consumes ELEMENTS_PER_BLOCK = 2 * blockDim.x elements:
//   - Loads them into shared memory.
//   - Up-sweep (reduce) to compute partial sums.
//   - Stores total to block_sums[blockIdx.x] (used for the next pass).
//   - Down-sweep produces the *exclusive* scan in shared mem.
//   - Adds the original element back to convert exclusive -> inclusive,
//     and writes results to global memory.
//
// Out-of-range indices (when N is not a multiple of ELEMENTS_PER_BLOCK)
// are zero-padded so the algorithm is uniform across blocks.
// ---------------------------------------------------------------------------
__global__ void block_scan_kernel(const Value* __restrict__ x,
                                  Value* __restrict__ y,
                                  Value* __restrict__ block_sums,
                                  long long N) {
  __shared__ Value sdata[ELEMENTS_PER_BLOCK];

  int tid = threadIdx.x;
  long long block_offset = (long long)blockIdx.x * ELEMENTS_PER_BLOCK;

  long long ai = block_offset + tid;
  long long bi = block_offset + tid + BLOCK_SIZE;

  // Load with zero-padding for tail block.
  Value va = (ai < N) ? x[ai] : (Value)0;
  Value vb = (bi < N) ? x[bi] : (Value)0;
  sdata[tid] = va;
  sdata[tid + BLOCK_SIZE] = vb;

  // ---- Up-sweep (reduce) ----
  int offset = 1;
  for (int d = ELEMENTS_PER_BLOCK >> 1; d > 0; d >>= 1) {
    __syncthreads();
    if (tid < d) {
      int aidx = offset * (2 * tid + 1) - 1;
      int bidx = offset * (2 * tid + 2) - 1;
      sdata[bidx] += sdata[aidx];
    }
    offset <<= 1;
  }

  // ---- Save total sum, clear last element to start exclusive scan ----
  if (tid == 0) {
    if (block_sums) {
      block_sums[blockIdx.x] = sdata[ELEMENTS_PER_BLOCK - 1];
    }
    sdata[ELEMENTS_PER_BLOCK - 1] = (Value)0;
  }

  // ---- Down-sweep ----
  for (int d = 1; d < ELEMENTS_PER_BLOCK; d <<= 1) {
    offset >>= 1;
    __syncthreads();
    if (tid < d) {
      int aidx = offset * (2 * tid + 1) - 1;
      int bidx = offset * (2 * tid + 2) - 1;
      Value t = sdata[aidx];
      sdata[aidx] = sdata[bidx];
      sdata[bidx] += t;
    }
  }
  __syncthreads();

  // sdata now contains the *exclusive* scan of the loaded elements.
  // Convert exclusive -> inclusive by adding the original value, and write.
  if (ai < N) {
    y[ai] = sdata[tid] + va;
  }
  if (bi < N) {
    y[bi] = sdata[tid + BLOCK_SIZE] + vb;
  }
}

// ---------------------------------------------------------------------------
// Kernel: add the exclusive-scanned per-block offset back to each element.
//   y[i] += block_offsets[blockIdx.x]
// where block_offsets is the EXCLUSIVE scan of block_sums.
// ---------------------------------------------------------------------------
__global__ void add_block_offsets_kernel(Value* __restrict__ y,
                                         const Value* __restrict__ block_offsets,
                                         long long N) {
  long long block_offset_idx = blockIdx.x;
  Value off = block_offsets[block_offset_idx];

  long long base = (long long)blockIdx.x * ELEMENTS_PER_BLOCK;
  int tid = threadIdx.x;
  long long ai = base + tid;
  long long bi = base + tid + BLOCK_SIZE;
  if (ai < N) y[ai] += off;
  if (bi < N) y[bi] += off;
}

// ---------------------------------------------------------------------------
// Convert a length-M inclusive scan into an exclusive scan in place.
// We need this because block_scan_kernel produces an INCLUSIVE scan, but
// to add the per-block offsets we need the EXCLUSIVE scan of the per-block
// sums (the offset for block 0 is 0, for block 1 is sum of block 0, etc.).
//
// Instead of writing a separate kernel, we save the original per-block sums
// before the recursive scan and recompute exclusive via:
//   exclusive[i] = inclusive[i] - original[i]
// which we fold into add_block_offsets_kernel by passing
// exclusive_block_sums explicitly.
// ---------------------------------------------------------------------------
__global__ void incl_to_excl_kernel(Value* __restrict__ excl,
                                    const Value* __restrict__ incl,
                                    const Value* __restrict__ original,
                                    long long M) {
  long long idx = (long long)blockIdx.x * blockDim.x + threadIdx.x;
  if (idx < M) {
    excl[idx] = incl[idx] - original[idx];
  }
}

// ---------------------------------------------------------------------------
// Recursive scan dispatcher.
//
// Performs an inclusive scan of `d_in` of length M and writes it to `d_out`.
// May allocate temporary device memory internally.
// ---------------------------------------------------------------------------
static void inclusive_scan_recursive(const Value* d_in, Value* d_out, long long M) {
  if (M <= 0) return;

  long long num_blocks = (M + ELEMENTS_PER_BLOCK - 1) / ELEMENTS_PER_BLOCK;

  Value* d_block_sums = nullptr;
  CUDA_CHECK(cudaMalloc(&d_block_sums, num_blocks * sizeof(Value)));

  // Pass 1: per-block inclusive scan; emit per-block totals into d_block_sums.
  block_scan_kernel<<<(int)num_blocks, BLOCK_SIZE>>>(d_in, d_out, d_block_sums, M);
  CUDA_CHECK(cudaGetLastError());

  if (num_blocks <= 1) {
    cudaFree(d_block_sums);
    return;
  }

  // Pass 2: scan the per-block totals.
  Value* d_block_inclusive = nullptr;
  CUDA_CHECK(cudaMalloc(&d_block_inclusive, num_blocks * sizeof(Value)));

  inclusive_scan_recursive(d_block_sums, d_block_inclusive, num_blocks);

  // Convert inclusive -> exclusive: excl = incl - original.
  Value* d_block_exclusive = nullptr;
  CUDA_CHECK(cudaMalloc(&d_block_exclusive, num_blocks * sizeof(Value)));
  int threads = 256;
  int blocks = (int)((num_blocks + threads - 1) / threads);
  incl_to_excl_kernel<<<blocks, threads>>>(d_block_exclusive, d_block_inclusive,
                                           d_block_sums, num_blocks);
  CUDA_CHECK(cudaGetLastError());

  // Pass 3: add per-block offsets.
  add_block_offsets_kernel<<<(int)num_blocks, BLOCK_SIZE>>>(d_out, d_block_exclusive, M);
  CUDA_CHECK(cudaGetLastError());

  cudaFree(d_block_sums);
  cudaFree(d_block_inclusive);
  cudaFree(d_block_exclusive);
}

int main(int argc, char* argv[]) {
  long long N = 32;
  if (argc == 2) N = std::atoll(argv[1]);
  if (N <= 0) {
    std::cerr << "ERROR: N must be positive (got " << N << ")\n";
    return 1;
  }

  std::cout << "Executing CUDA prefix sum with N = " << N << "\n";

  // Device info
  int dev = 0;
  cudaDeviceProp prop{};
  CUDA_CHECK(cudaGetDevice(&dev));
  CUDA_CHECK(cudaGetDeviceProperties(&prop, dev));
  std::cout << "GPU: " << prop.name << " (CC " << prop.major << "." << prop.minor
            << ")\n";
  std::cout << "BLOCK_SIZE = " << BLOCK_SIZE
            << ", ELEMENTS_PER_BLOCK = " << ELEMENTS_PER_BLOCK << "\n";

  // ---- Allocate device memory ----
  Value* d_x = nullptr;
  Value* d_y = nullptr;
  CUDA_CHECK(cudaMalloc(&d_x, N * sizeof(Value)));
  CUDA_CHECK(cudaMalloc(&d_y, N * sizeof(Value)));

  // ---- CUDA timing events ----
  cudaEvent_t e_total_start, e_total_stop, e_compute_start, e_compute_stop;
  cudaEventCreate(&e_total_start);
  cudaEventCreate(&e_total_stop);
  cudaEventCreate(&e_compute_start);
  cudaEventCreate(&e_compute_stop);

  cudaEventRecord(e_total_start);

  // ---- Generate input on the device ----
  {
    int threads = 256;
    int blocks = (int)((N + threads - 1) / threads);
    generate_input_kernel<<<blocks, threads>>>(d_x, N);
    CUDA_CHECK(cudaGetLastError());
  }

  // ---- Compute (this is the timed scan kernel chain) ----
  cudaEventRecord(e_compute_start);
  inclusive_scan_recursive(d_x, d_y, N);
  cudaEventRecord(e_compute_stop);

  // ---- Copy result back ----
  std::vector<Value> y(N);
  CUDA_CHECK(cudaMemcpy(y.data(), d_y, N * sizeof(Value), cudaMemcpyDeviceToHost));

  cudaEventRecord(e_total_stop);
  cudaEventSynchronize(e_total_stop);

  float compute_ms = 0.0f, total_ms = 0.0f;
  cudaEventElapsedTime(&compute_ms, e_compute_start, e_compute_stop);
  cudaEventElapsedTime(&total_ms, e_total_start, e_total_stop);

  std::cout << "CUDA scan (kernels only): " << compute_ms << " ms\n";
  std::cout << "CUDA total (gen+scan+D2H): " << total_ms << " ms\n";

  // ---- Write output ----
  std::string filename = "scan_N" + std::to_string(N) + ".txt";
  std::ofstream ofs(filename);
  if (!ofs) {
    std::cerr << "ERROR: cannot open output file " << filename << "\n";
    return 1;
  }
  for (long long i = 0; i < N; ++i) ofs << y[i] << "\n";
  ofs.close();
  std::cout << "Wrote result to " << filename << "\n";

  if (N <= 100) {
    std::cout << "y =";
    for (long long i = 0; i < N; ++i) std::cout << " " << y[i];
    std::cout << "\n";
  }

  // ---- Cleanup ----
  cudaEventDestroy(e_total_start);
  cudaEventDestroy(e_total_stop);
  cudaEventDestroy(e_compute_start);
  cudaEventDestroy(e_compute_stop);
  cudaFree(d_x);
  cudaFree(d_y);

  return 0;
}
