/*
 * Foundations of Parallel Computing II.
 * CUDA implementation of inclusive prefix sum (scan).
 *
 * Input is generated by:
 *   x[i] = (i * 17 + 13) % 1000
 *
 * Three-pass scheme:
 *   1. Per-block local inclusive scan in shared memory (work-efficient
 *      Blelloch up-sweep / down-sweep), each block writes its total sum
 *      to a per-block sums array.
 *   2. Recursively scan the per-block sums array (exclusive scan of the
 *      per-block totals, performed by the same kernel chain).
 *   3. Add the corresponding block offset back to every element of each
 *      block's local result to produce the final inclusive scan.
 *
 * On completion, the result is written to:
 *   scan_N<N>.txt
 *
 * Usage: ./parallel <N>
 */

#include <cuda_runtime.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#define CUDA_CHECK(call)                                                       \
  do {                                                                         \
    cudaError_t err__ = (call);                                                \
    if (err__ != cudaSuccess) {                                                \
      std::cerr << "CUDA error " << cudaGetErrorString(err__) << " at "        \
                << __FILE__ << ":" << __LINE__ << "\n";                        \
      std::exit(1);                                                            \
    }                                                                          \
  } while (0)

// ---------------------------------------------------------------------------
// Tunable parameters
// ---------------------------------------------------------------------------
//
// Each thread processes 2 elements (Blelloch tree on 2*BLOCK_SIZE elements
// per block). BLOCK_SIZE is the number of threads per block.
static const int BLOCK_SIZE = 256;
static const int ELEMENTS_PER_BLOCK = 2 * BLOCK_SIZE;

using Input = int;     // input values are < 1000, int32 is plenty
using Value = long long;  // accumulator / block sums / output: must hold > 2^31

// ---------------------------------------------------------------------------
// Kernel: generate input on the device (int32 — every value < 1000)
// ---------------------------------------------------------------------------
__global__ void generate_input_kernel(Input* x, long long N) {
  long long idx = (long long)blockIdx.x * blockDim.x + threadIdx.x;
  if (idx < N) {
    x[idx] = (int)((idx * 17LL + 13LL) % 1000LL);
  }
}

// ---------------------------------------------------------------------------
// Kernel: per-block inclusive scan using Blelloch's algorithm in shared mem.
//
// Each block consumes ELEMENTS_PER_BLOCK = 2 * blockDim.x elements:
//   - Loads them into shared memory.
//   - Up-sweep (reduce) to compute partial sums.
//   - Stores total to block_sums[blockIdx.x] (used for the next pass).
//   - Down-sweep produces the *exclusive* scan in shared mem.
//   - Adds the original element back to convert exclusive -> inclusive,
//     and writes results to global memory.
//
// Out-of-range indices (when N is not a multiple of ELEMENTS_PER_BLOCK)
// are zero-padded so the algorithm is uniform across blocks.
//
// Bank-conflict-free shared memory layout (GPU Gems 3, §39.2.3): we pad
// every NUM_BANKS-th slot. Effective index = i + (i >> LOG_NUM_BANKS).
// This eliminates the 32-way conflicts the naive `2*tid+1` indexing
// causes when adjacent threads stride by powers of 2.
// ---------------------------------------------------------------------------
#define LOG_NUM_BANKS 5
#define CONFLICT_FREE_OFFSET(n) ((n) >> LOG_NUM_BANKS)
#define SDATA_PADDED_SIZE \
  (ELEMENTS_PER_BLOCK + CONFLICT_FREE_OFFSET(ELEMENTS_PER_BLOCK - 1) + 1)
#define SI(i) ((i) + CONFLICT_FREE_OFFSET(i))

__global__ void block_scan_kernel_top(const Input* __restrict__ x,
                                      Value* __restrict__ y,
                                      Value* __restrict__ block_sums,
                                      long long N) {
  __shared__ Value sdata[SDATA_PADDED_SIZE];

  int tid = threadIdx.x;
  long long block_offset = (long long)blockIdx.x * ELEMENTS_PER_BLOCK;

  long long ai = block_offset + tid;
  long long bi = block_offset + tid + BLOCK_SIZE;

  // Read int32 input, promote to long long in shared mem.
  // Interleaved layout (sdata[tid], sdata[tid+BLOCK_SIZE]) is preserved from
  // v2 — that pattern already coalesces over warp lanes and stays
  // bank-conflict-free under the SI() padding.
  Value va = (ai < N) ? (Value)x[ai] : (Value)0;
  Value vb = (bi < N) ? (Value)x[bi] : (Value)0;
  sdata[SI(tid)] = va;
  sdata[SI(tid + BLOCK_SIZE)] = vb;

  // ---- Up-sweep (reduce) ----
  int offset = 1;
  for (int d = ELEMENTS_PER_BLOCK >> 1; d > 0; d >>= 1) {
    __syncthreads();
    if (tid < d) {
      int aidx = offset * (2 * tid + 1) - 1;
      int bidx = offset * (2 * tid + 2) - 1;
      sdata[SI(bidx)] += sdata[SI(aidx)];
    }
    offset <<= 1;
  }

  // ---- Save total sum, clear last element to start exclusive scan ----
  if (tid == 0) {
    int last = ELEMENTS_PER_BLOCK - 1;
    if (block_sums) {
      block_sums[blockIdx.x] = sdata[SI(last)];
    }
    sdata[SI(last)] = (Value)0;
  }

  // ---- Down-sweep ----
  for (int d = 1; d < ELEMENTS_PER_BLOCK; d <<= 1) {
    offset >>= 1;
    __syncthreads();
    if (tid < d) {
      int aidx = offset * (2 * tid + 1) - 1;
      int bidx = offset * (2 * tid + 2) - 1;
      Value t = sdata[SI(aidx)];
      sdata[SI(aidx)] = sdata[SI(bidx)];
      sdata[SI(bidx)] += t;
    }
  }
  __syncthreads();

  if (ai < N) y[ai] = sdata[SI(tid)] + va;
  if (bi < N) y[bi] = sdata[SI(tid + BLOCK_SIZE)] + vb;
}

__global__ void block_scan_kernel(const Value* __restrict__ x,
                                  Value* __restrict__ y,
                                  Value* __restrict__ block_sums,
                                  long long N) {
  __shared__ Value sdata[SDATA_PADDED_SIZE];

  int tid = threadIdx.x;
  long long block_offset = (long long)blockIdx.x * ELEMENTS_PER_BLOCK;

  long long ai = block_offset + tid;
  long long bi = block_offset + tid + BLOCK_SIZE;

  // Load with zero-padding for tail block.
  Value va = (ai < N) ? x[ai] : (Value)0;
  Value vb = (bi < N) ? x[bi] : (Value)0;
  sdata[SI(tid)] = va;
  sdata[SI(tid + BLOCK_SIZE)] = vb;

  // ---- Up-sweep (reduce) ----
  int offset = 1;
  for (int d = ELEMENTS_PER_BLOCK >> 1; d > 0; d >>= 1) {
    __syncthreads();
    if (tid < d) {
      int aidx = offset * (2 * tid + 1) - 1;
      int bidx = offset * (2 * tid + 2) - 1;
      sdata[SI(bidx)] += sdata[SI(aidx)];
    }
    offset <<= 1;
  }

  // ---- Save total sum, clear last element to start exclusive scan ----
  if (tid == 0) {
    int last = ELEMENTS_PER_BLOCK - 1;
    if (block_sums) {
      block_sums[blockIdx.x] = sdata[SI(last)];
    }
    sdata[SI(last)] = (Value)0;
  }

  // ---- Down-sweep ----
  for (int d = 1; d < ELEMENTS_PER_BLOCK; d <<= 1) {
    offset >>= 1;
    __syncthreads();
    if (tid < d) {
      int aidx = offset * (2 * tid + 1) - 1;
      int bidx = offset * (2 * tid + 2) - 1;
      Value t = sdata[SI(aidx)];
      sdata[SI(aidx)] = sdata[SI(bidx)];
      sdata[SI(bidx)] += t;
    }
  }
  __syncthreads();

  // sdata now contains the *exclusive* scan of the loaded elements.
  // Convert exclusive -> inclusive by adding the original value, and write.
  if (ai < N) {
    y[ai] = sdata[SI(tid)] + va;
  }
  if (bi < N) {
    y[bi] = sdata[SI(tid + BLOCK_SIZE)] + vb;
  }
}

// ---------------------------------------------------------------------------
// Kernel: add the per-block offset back to each element.
//
// The recursive call leaves `block_inclusive[bid]` containing the inclusive
// scan of the per-block totals. The *exclusive* offset we actually want is
//   off = block_inclusive[bid] - block_sums[bid]   (i.e. inclusive - own).
// We compute this in registers here so we never need a separate
// inclusive->exclusive kernel.
// ---------------------------------------------------------------------------
__global__ void add_block_offsets_kernel(Value* __restrict__ y,
                                         const Value* __restrict__ block_inclusive,
                                         const Value* __restrict__ block_sums,
                                         long long N) {
  int bid = blockIdx.x;
  Value off = block_inclusive[bid] - block_sums[bid];

  long long base = (long long)bid * ELEMENTS_PER_BLOCK;
  int tid = threadIdx.x;
  long long ai = base + tid;
  long long bi = base + tid + BLOCK_SIZE;
  if (ai < N) y[ai] += off;
  if (bi < N) y[bi] += off;
}

// ---------------------------------------------------------------------------
// Worst-case workspace size (in Value slots) for an N-element scan.
// At each level we need 2 * num_blocks slots (block_sums + block_inclusive).
// The total is bounded by 2 * (N/EPB + N/EPB^2 + ...) <= 2*N/(EPB-1),
// i.e. tiny next to N itself.
// ---------------------------------------------------------------------------
static long long scan_workspace_size(long long N) {
  long long total = 0;
  long long m = N;
  while (m > 1) {
    long long nb = (m + ELEMENTS_PER_BLOCK - 1) / ELEMENTS_PER_BLOCK;
    total += 2 * nb;
    m = nb;
  }
  return total > 0 ? total : 1;  // avoid cudaMalloc(0)
}

// ---------------------------------------------------------------------------
// Recursive scan dispatcher.
//
// Performs an inclusive scan of `d_in` of length M and writes it to `d_out`.
// `workspace` points to a pre-allocated device buffer (sized by
// scan_workspace_size). `workspace_used` is how many Value slots are
// already consumed by callers further up the stack, so we slice from the
// tail. No cudaMalloc/cudaFree on the hot path.
// ---------------------------------------------------------------------------
static void inclusive_scan_recursive(const Value* d_in, Value* d_out,
                                     long long M, Value* workspace,
                                     long long workspace_used) {
  if (M <= 0) return;

  long long num_blocks = (M + ELEMENTS_PER_BLOCK - 1) / ELEMENTS_PER_BLOCK;

  // Slice block_sums and block_inclusive from the workspace at this level.
  Value* d_block_sums = workspace + workspace_used;
  Value* d_block_inclusive = d_block_sums + num_blocks;
  long long new_used = workspace_used + 2 * num_blocks;

  // Pass 1: per-block inclusive scan; emit per-block totals into d_block_sums.
  block_scan_kernel<<<(int)num_blocks, BLOCK_SIZE>>>(d_in, d_out, d_block_sums, M);
  CUDA_CHECK(cudaGetLastError());

  if (num_blocks <= 1) return;

  // Pass 2: scan the per-block totals (recurse).
  inclusive_scan_recursive(d_block_sums, d_block_inclusive, num_blocks,
                           workspace, new_used);

  // Pass 3: add per-block exclusive offsets, computed in-register from
  // (inclusive - original) inside the kernel — no separate incl->excl pass.
  add_block_offsets_kernel<<<(int)num_blocks, BLOCK_SIZE>>>(
      d_out, d_block_inclusive, d_block_sums, M);
  CUDA_CHECK(cudaGetLastError());
}

// ---------------------------------------------------------------------------
// Top-level scan: reads from an `Input*` (int32) source, writes a Value
// (long long) inclusive scan. Subsequent levels stay all-`Value`.
// ---------------------------------------------------------------------------
static void inclusive_scan_top(const Input* d_in, Value* d_out, long long N,
                               Value* workspace) {
  if (N <= 0) return;

  long long num_blocks = (N + ELEMENTS_PER_BLOCK - 1) / ELEMENTS_PER_BLOCK;

  Value* d_block_sums = workspace;
  Value* d_block_inclusive = d_block_sums + num_blocks;
  long long new_used = 2 * num_blocks;

  block_scan_kernel_top<<<(int)num_blocks, BLOCK_SIZE>>>(d_in, d_out,
                                                         d_block_sums, N);
  CUDA_CHECK(cudaGetLastError());

  if (num_blocks <= 1) return;

  inclusive_scan_recursive(d_block_sums, d_block_inclusive, num_blocks,
                           workspace, new_used);

  add_block_offsets_kernel<<<(int)num_blocks, BLOCK_SIZE>>>(
      d_out, d_block_inclusive, d_block_sums, N);
  CUDA_CHECK(cudaGetLastError());
}

int main(int argc, char* argv[]) {
  long long N = 32;
  if (argc == 2) N = std::atoll(argv[1]);
  if (N <= 0) {
    std::cerr << "ERROR: N must be positive (got " << N << ")\n";
    return 1;
  }

  std::cout << "Executing CUDA prefix sum with N = " << N << "\n";

  // Device info
  int dev = 0;
  cudaDeviceProp prop{};
  CUDA_CHECK(cudaGetDevice(&dev));
  CUDA_CHECK(cudaGetDeviceProperties(&prop, dev));
  std::cout << "GPU: " << prop.name << " (CC " << prop.major << "." << prop.minor
            << ")\n";
  std::cout << "BLOCK_SIZE = " << BLOCK_SIZE
            << ", ELEMENTS_PER_BLOCK = " << ELEMENTS_PER_BLOCK << "\n";

  // ---- Allocate device memory ----
  Input* d_x = nullptr;  // int32 — values are < 1000
  Value* d_y = nullptr;  // long long — y[N-1] can exceed 2^31
  CUDA_CHECK(cudaMalloc(&d_x, N * sizeof(Input)));
  CUDA_CHECK(cudaMalloc(&d_y, N * sizeof(Value)));

  // Pre-allocate scan workspace (block_sums + block_inclusive arrays for all
  // recursion levels, sized once) so the recursive dispatcher does not call
  // cudaMalloc on the timed path.
  Value* d_workspace = nullptr;
  long long workspace_slots = scan_workspace_size(N);
  CUDA_CHECK(cudaMalloc(&d_workspace, workspace_slots * sizeof(Value)));

  // ---- CUDA timing events ----
  cudaEvent_t e_total_start, e_total_stop, e_compute_start, e_compute_stop;
  cudaEventCreate(&e_total_start);
  cudaEventCreate(&e_total_stop);
  cudaEventCreate(&e_compute_start);
  cudaEventCreate(&e_compute_stop);

  cudaEventRecord(e_total_start);

  // ---- Generate input on the device ----
  {
    int threads = 256;
    int blocks = (int)((N + threads - 1) / threads);
    generate_input_kernel<<<blocks, threads>>>(d_x, N);
    CUDA_CHECK(cudaGetLastError());
  }

  // ---- Compute (this is the timed scan kernel chain) ----
  cudaEventRecord(e_compute_start);
  inclusive_scan_top(d_x, d_y, N, d_workspace);
  cudaEventRecord(e_compute_stop);

  // ---- Copy result back ----
  std::vector<Value> y(N);
  CUDA_CHECK(cudaMemcpy(y.data(), d_y, N * sizeof(Value), cudaMemcpyDeviceToHost));

  cudaEventRecord(e_total_stop);
  cudaEventSynchronize(e_total_stop);

  float compute_ms = 0.0f, total_ms = 0.0f;
  cudaEventElapsedTime(&compute_ms, e_compute_start, e_compute_stop);
  cudaEventElapsedTime(&total_ms, e_total_start, e_total_stop);

  std::cout << "CUDA scan (kernels only): " << compute_ms << " ms\n";
  std::cout << "CUDA total (gen+scan+D2H): " << total_ms << " ms\n";

  // ---- Write output ----
  std::string filename = "scan_N" + std::to_string(N) + ".txt";
  std::ofstream ofs(filename);
  if (!ofs) {
    std::cerr << "ERROR: cannot open output file " << filename << "\n";
    return 1;
  }
  for (long long i = 0; i < N; ++i) ofs << y[i] << "\n";
  ofs.close();
  std::cout << "Wrote result to " << filename << "\n";

  if (N <= 100) {
    std::cout << "y =";
    for (long long i = 0; i < N; ++i) std::cout << " " << y[i];
    std::cout << "\n";
  }

  // ---- Cleanup ----
  cudaEventDestroy(e_total_start);
  cudaEventDestroy(e_total_stop);
  cudaEventDestroy(e_compute_start);
  cudaEventDestroy(e_compute_stop);
  cudaFree(d_x);
  cudaFree(d_y);
  cudaFree(d_workspace);

  return 0;
}
