/*
 * Foundations of Parallel Computing II.
 * Serial implementation of inclusive prefix sum.
 *
 * Input is generated by:
 *   x[i] = (i * 17 + 13) % 1000
 *
 * On completion, the result is written to:
 *   scan_N<N>.txt
 *
 * Usage: ./serial <N>
 */

#include <chrono>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

inline long long x_elem(long long i) {
  return (i * 17LL + 13LL) % 1000LL;
}

int main(int argc, char* argv[]) {
  long long N = 32;
  if (argc == 2) N = std::atoll(argv[1]);

  std::cout << "Executing serial prefix sum with N = " << N << "\n";

  std::vector<long long> x(N);
  std::vector<long long> y(N);

  for (long long i = 0; i < N; ++i) {
    x[i] = x_elem(i);
  }

  auto t0 = std::chrono::high_resolution_clock::now();
  if (N > 0) {
    y[0] = x[0];
    for (long long i = 1; i < N; ++i) {
      y[i] = y[i - 1] + x[i];
    }
  }
  auto t1 = std::chrono::high_resolution_clock::now();

  double ms = std::chrono::duration<double, std::milli>(t1 - t0).count();
  std::cout << "Serial compute time: " << ms << " ms\n";

  std::string filename = "scan_N" + std::to_string(N) + ".txt";
  std::ofstream ofs(filename);
  if (!ofs) {
    std::cerr << "ERROR: cannot open output file " << filename << "\n";
    return 1;
  }
  for (long long i = 0; i < N; ++i) ofs << y[i] << "\n";
  ofs.close();

  std::cout << "Wrote result to " << filename << "\n";
  if (N <= 100) {
    std::cout << "y =";
    for (long long i = 0; i < N; ++i) std::cout << " " << y[i];
    std::cout << "\n";
  }

  return 0;
}
