/*
 * Foundations of Parallel Computing II.
 * This is a TEMPLATE for MPI parallel implementation of matrix-vector
 * multiplication y = A * x.
 *
 * Matrix A and vector x are generated by deterministic formulas:
 *   A[i][j] = (i*7 + j*13) % 1000
 *   x[j]    = (j*3 + 1)    % 100
 * Each process generates its own rows of A locally (no communication needed
 * for initialization).
 *
 * On completion, rank 0 writes the result vector y to a file
 *   y_N<N>.txt
 * with one integer per line. This file is the input to verify.py.
 *
 * Usage: mpirun -np <P> ./parallel <N>
 */

#include <cstdlib>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#include <mpi.h>

inline long long A_elem(long i, long j) {
  return (i * 7LL + j * 13LL) % 1000;
}

inline long long x_elem(long j) {
  return (j * 3LL + 1) % 100;
}

int main(int argc, char* argv[]) {
  long N;
  int rank, size;
  MPI_Init(&argc, &argv);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  MPI_Comm_size(MPI_COMM_WORLD, &size);

  if (argc < 2)
    N = 32;
  else
    N = std::atol(argv[1]);

  if (rank == 0) {
    std::cout << "Executing with N = " << N << ", comm size = " << size << "\n";
  }

  // 任务划分：把 A 的 N 行按块划分给 size 个进程
  // 提示：如果 N 不能被 size 整除，请合理处理余数（可在报告中说明）
  long start        = /* Fill in your code */;
  long end          = /* Fill in your code */;
  long local_rows   = /* Fill in your code */;

  // 初始化向量 x：每个进程都保留一份完整副本（公式确定，无需通信）
  std::vector<long long> x(N);
  /* Fill in your code: 用 x_elem(j) 填充 x */

  // 初始化本地的 A 行块（行 start..end-1，每行 N 列）
  std::vector<long long> local_A(local_rows * N);
  /* Fill in your code: 用 A_elem(start + i, j) 填充 local_A */

  // 计算本地结果 local_y = local_A * x
  std::vector<long long> local_y(local_rows, 0);
  /* Fill in your code */

  // 通信：把所有进程的 local_y 收集到 rank 0 的完整 y
  std::vector<long long> y;
  if (rank == 0) y.resize(N);
  /* Fill in your code: MPI_Gather 或 MPI_Gatherv（N 不被 size 整除时） */

  // 写出结果文件并打印摘要（只在 rank 0 上执行）
  // 该段已为你写好，无需修改 —— 保证 verify.py 能正确读取
  if (rank == 0) {
    std::string filename = "y_N" + std::to_string(N) + ".txt";
    std::ofstream ofs(filename);
    if (!ofs) {
      std::cerr << "ERROR: cannot open output file " << filename << "\n";
      MPI_Abort(MPI_COMM_WORLD, 1);
    }
    for (long i = 0; i < N; ++i) ofs << y[i] << "\n";
    ofs.close();
    std::cout << "Wrote result to " << filename << "\n";

    // 对小规模情形（N <= 100），同时打印到终端，便于截图核对
    if (N <= 100) {
      std::cout << "y =";
      for (long i = 0; i < N; ++i) std::cout << " " << y[i];
      std::cout << "\n";
    }
  }

  MPI_Finalize();
  return 0;
}
