/*
 * Foundations of Parallel Computing II.
 * MPI parallel implementation of matrix-vector multiplication y = A * x.
 *
 * Matrix A and vector x are generated by deterministic formulas:
 *   A[i][j] = (i*7 + j*13) % 1000
 *   x[j]    = (j*3 + 1)    % 100
 * Each process generates its own rows of A locally (no communication needed
 * for initialization).
 *
 * Strategy:
 *   1D row-block partitioning. The N rows of A are split among `size`
 *   processes. The first (N mod size) ranks own one extra row so that the
 *   load is as balanced as possible when N is not divisible by size. We use
 *   MPI_Gatherv unconditionally (it degenerates to a Gather when N is
 *   divisible by size), which makes the communication step uniform across
 *   all three test cases (N = 32, 1000, 8192).
 *
 * Timing:
 *   We bracket the whole compute + communication phase with MPI_Barrier
 *   followed by MPI_Wtime, as recommended in the assignment. The local
 *   initialization of A and x is excluded from the timed section because the
 *   serial reference does not pay for any "data distribution" either.
 *
 * On completion, rank 0 writes the result vector y to a file
 *   y_N<N>.txt
 * with one integer per line. This file is the input to verify.py.
 *
 * Usage: mpirun -np <P> ./parallel <N>
 */

#include <cstdlib>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#include <mpi.h>

inline long long A_elem(long i, long j) {
  return (i * 7LL + j * 13LL) % 1000;
}

inline long long x_elem(long j) {
  return (j * 3LL + 1) % 100;
}

int main(int argc, char* argv[]) {
  long N;
  int rank, size;
  MPI_Init(&argc, &argv);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  MPI_Comm_size(MPI_COMM_WORLD, &size);

  if (argc < 2)
    N = 32;
  else
    N = std::atol(argv[1]);

  if (rank == 0) {
    std::cout << "Executing with N = " << N << ", comm size = " << size << "\n";
  }

  // -----------------------------------------------------------------------
  // 任务划分：把 A 的 N 行按块划分给 size 个进程
  // 当 N 不能整除 size 时，前 (N % size) 个进程各多分到 1 行，其余进程少 1
  // 行；这样每两个进程拥有的行数最多相差 1，负载最均衡。
  // -----------------------------------------------------------------------
  long base       = N / size;
  long rem        = N % size;
  long start      = rank * base + (rank < rem ? rank : rem);
  long local_rows = base + (rank < rem ? 1 : 0);
  // 'end' variable removed because the inner loop bounds with local_rows directly.
  // long end     = start + local_rows;

  // -----------------------------------------------------------------------
  // 初始化向量 x：每个进程都保留一份完整副本（公式确定，无需通信）
  // -----------------------------------------------------------------------
  std::vector<long long> x(N);
  for (long j = 0; j < N; ++j) x[j] = x_elem(j);

  // -----------------------------------------------------------------------
  // 初始化本地的 A 行块（行 start..end-1，每行 N 列），按行优先存储
  // -----------------------------------------------------------------------
  std::vector<long long> local_A(static_cast<size_t>(local_rows) * N);
  for (long i = 0; i < local_rows; ++i) {
    long gi = start + i;
    long long* row = local_A.data() + static_cast<size_t>(i) * N;
    for (long j = 0; j < N; ++j) {
      row[j] = A_elem(gi, j);
    }
  }

  // -----------------------------------------------------------------------
  // 为 MPI_Gatherv 准备 recvcounts[] 与 displs[]（仅在 rank 0 上必须正确，
  // 但所有进程一起构造也无妨，便于调试）。注意 N 可能很大，但 recvcounts
  // 是元素个数（int），N <= 8192 时不会溢出 int。
  // -----------------------------------------------------------------------
  std::vector<int> recvcounts(size), displs(size);
  for (int r = 0; r < size; ++r) {
    long cnt = base + (r < rem ? 1 : 0);
    long off = r * base + (r < rem ? r : rem);
    recvcounts[r] = static_cast<int>(cnt);
    displs[r]     = static_cast<int>(off);
  }

  // 为输出预留空间（仅 rank 0 真正使用）
  std::vector<long long> y;
  if (rank == 0) y.resize(N);

  // -----------------------------------------------------------------------
  // 计时段（MPI_Wtime + MPI_Barrier，符合作业要求）
  // -----------------------------------------------------------------------
  std::vector<long long> local_y(local_rows, 0);

  MPI_Barrier(MPI_COMM_WORLD);
  double t0 = MPI_Wtime();

  // 计算本地 local_y = local_A * x
  for (long i = 0; i < local_rows; ++i) {
    const long long* row = local_A.data() + static_cast<size_t>(i) * N;
    long long s = 0;
    for (long j = 0; j < N; ++j) s += row[j] * x[j];
    local_y[i] = s;
  }

  // 通信：把所有进程的 local_y 收集到 rank 0 的完整 y
  // 使用 MPI_Gatherv 以兼容 N 不被 size 整除的情况；当能整除时，
  // recvcounts 全部相等、displs 等差，Gatherv 退化为普通 Gather。
  MPI_Gatherv(local_y.data(),
              static_cast<int>(local_rows),
              MPI_LONG_LONG,
              rank == 0 ? y.data() : nullptr,
              recvcounts.data(),
              displs.data(),
              MPI_LONG_LONG,
              0,
              MPI_COMM_WORLD);

  MPI_Barrier(MPI_COMM_WORLD);
  double t1 = MPI_Wtime();
  if (rank == 0) {
    std::cout << "time=" << (t1 - t0) << " s\n";
  }

  // -----------------------------------------------------------------------
  // 写出结果文件并打印摘要（只在 rank 0 上执行）
  // 该段已为你写好，无需修改 —— 保证 verify.py 能正确读取
  // -----------------------------------------------------------------------
  if (rank == 0) {
    std::string filename = "y_N" + std::to_string(N) + ".txt";
    std::ofstream ofs(filename);
    if (!ofs) {
      std::cerr << "ERROR: cannot open output file " << filename << "\n";
      MPI_Abort(MPI_COMM_WORLD, 1);
    }
    for (long i = 0; i < N; ++i) ofs << y[i] << "\n";
    ofs.close();
    std::cout << "Wrote result to " << filename << "\n";

    // 对小规模情形（N <= 100），同时打印到终端，便于截图核对
    if (N <= 100) {
      std::cout << "y =";
      for (long i = 0; i < N; ++i) std::cout << " " << y[i];
      std::cout << "\n";
    }
  }

  MPI_Finalize();
  return 0;
}
