/*
 * Foundations of Parallel Computing II.
 * Serial implementation of matrix-vector multiplication y = A * x.
 *
 * Matrix A and vector x are generated by deterministic formulas:
 *   A[i][j] = (i*7 + j*13) % 1000
 *   x[j]    = (j*3 + 1)    % 100
 *
 * On completion, the result vector y is written to a file
 *   y_N<N>.txt
 * with one integer per line. This file is the input to verify.py.
 *
 * Usage: ./serial <N>
 */

#include <cstdlib>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

inline long long A_elem(long i, long j) {
  return (i * 7LL + j * 13LL) % 1000;
}

inline long long x_elem(long j) {
  return (j * 3LL + 1) % 100;
}

int main(int argc, char* argv[]) {
  long N;

  if (argc != 2)
    N = 32;
  else
    N = std::atol(argv[1]);

  std::cout << "Executing serial version with N = " << N << "\n";

  // 初始化 x
  std::vector<long long> x(N);
  for (long j = 0; j < N; j++) {
    x[j] = x_elem(j);
  }

  // 计算 y = A * x
  std::vector<long long> y(N, 0);
  for (long i = 0; i < N; i++) {
    long long s = 0;
    for (long j = 0; j < N; j++) {
      s += A_elem(i, j) * x[j];
    }
    y[i] = s;
  }

  // 写入结果文件：每行一个整数，供 verify.py 验证
  std::string filename = "y_N" + std::to_string(N) + ".txt";
  std::ofstream ofs(filename);
  if (!ofs) {
    std::cerr << "ERROR: cannot open output file " << filename << "\n";
    return 1;
  }
  for (long i = 0; i < N; ++i) ofs << y[i] << "\n";
  ofs.close();
  std::cout << "Wrote result to " << filename << "\n";

  // 对小规模情形（N <= 100），同时打印到终端，便于截图核对
  if (N <= 100) {
    std::cout << "y =";
    for (long i = 0; i < N; i++) std::cout << " " << y[i];
    std::cout << "\n";
  }

  return 0;
}
